### ISSUE TITLE
ebayApiPostXmlRequest Callback being triggered twice 

### ISSUE THREAD

**Issue by brucexia0** [benbuckman/nodejs-ebay-api#16]
This is my code snippet that calls the function:

```    
ebay.ebayApiPostXmlRequest({
        serviceName: 'Trading',
        opType: 'GetOrders',
        devName: 'mobisoft',
....},function(error, results) {
        if (error) {
            console.dir(error);
            process.exit(1);
        }
        res.send(getAddresses(results.OrderArray.Order));<--line 39
    });
```
In my callback function I call res.send(...), this function is being triggered twice from ebay-api/index.js:417:7 which caused this exception.

It looks like the second one was triggered upon receiving response 304 but I cannot decrypt the https traffice.

< http.js:689
<     throw new Error('Can\'t set headers after they are sent.');
<           ^
< Error: Can't set headers after they are sent.
<     at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
<     at ServerResponse.header (/Users/brucexia/nodejs/ebayhelper/node_modules/express/lib/response.js:662:10)
<     at ServerResponse.json (/Users/brucexia/nodejs/ebayhelper/node_modules/express/lib/response.js:232:10)
<     at ServerResponse.send (/Users/brucexia/nodejs/ebayhelper/node_modules/express/lib/response.js:134:21)
<     at module.exports (/Users/brucexia/nodejs/ebayhelper/routes/orders.js:39:13)
<     at request.on.error.message (/Users/brucexia/nodejs/ebayhelper/node_modules/ebay-api/index.js:417:7)
<     at parseData (/Users/brucexia/nodejs/ebayhelper/node_modules/ebay-api/index.js:411:9)
<     at async.iterator.fn (/Users/brucexia/nodejs/ebayhelper/node_modules/ebay-api/node_modules/async/lib/async.js:517:34)
<     at async.waterfall.wrapIterator (/Users/brucexia/nodejs/ebayhelper/node_modules/ebay-api/node_modules/async/lib/async.js:441:34)
<     at process._tickCallback (node.js:419:13)

**Comment by nirco123** [comment]
anything new with this issue?

**Comment by cnaccio** [comment]
I'm also having this issue.

**Comment by cnaccio** [comment]
I was able to fix this issue by going into the ebay-api package.json, and updating restler from version ~2.0.1 to version ~3.2.2 and then from the ebay-api run npm install. After upgrading restler I no longer got the issue. Seeing as how this project doesn't seem to be active I'm thinking about forking it into a new library, or starting a new library as I'm currently working on a big project that will be using the ebay api extensively.

**Comment by benbuckman** [comment]
I assume this is no longer relevant in the 2.x branch, please re-open if that's not true.
Thanks
