### ISSUE TITLE
Issue with appID in getRequest

### ISSUE THREAD

**Issue by Datise** [benbuckman/nodejs-ebay-api#17]
Hi, I'm new to coding and building a school project that connects to ebay trading. Keep trying to formulate an ebayApiGetRequest with this package but I always seem to run into this error after sending the request.
[SyntaxError: Unexpected token <] .
I've taken out lines individually and it seems to occur whenever I add my personal app id. Project wide search yielding no help. Are there any known issues/conflicts?

**Comment by Datise** [comment]
Thanks again for the code it fixed my get request issue. The trading issue was silly, using get instead of postxml.

**Comment by chovy** [comment]
Can someone put a clear example of how to use an affiliate id?
