### ISSUE TITLE
Nested objects are not handled properly in  options.params 

### ISSUE THREAD

**Issue by dali-ifg** [benbuckman/nodejs-ebay-api#7]
If you try to pass a params object that has a nested object inside it, the xml serialization doesn't work properly.

{code}
params : {
      authToken : 'AuthToken',
      ItemID    : 'itemId',
      //    'CreateTimeFrom' : '2013-10-13T00:00:00.0',
      //    'CreateTimeTo' : '2013-10-27T00:00:00.0',
      MemberMessage :
      {
        Body : ['Hello,',
        'There'].join('\n'),
        QuestionType: 'General',
        RecipientID :  'ReceipientId',
        Subject     : 'My Store'
      }
    }
{code}

The XML you get in this case doesn't include the contents of MemberMessage and you get <MemberMessage/>. That's it.

(this is an example trying to use the AddMemberMessageAAQToPartner eBay API Method to send an ebay message to a buyer (http://developer.ebay.com/Devzone/XML/docs/Reference/eBay/AddMemberMessageAAQToPartner.html)

**Comment by benbuckman** [comment]
This code has been heavily refactored in the 2.x branch, so I'll close this.

**Comment by benbuckman** [comment]
Note, there is a bug in the 2.x branch, possibly similar to this one, reported here: #25
